#!/bin/bash

# Find out the directory in which we reside
cd $( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/..
source local.rc
export FLOWGENCYTM_USER MOJO_LISTEN
[ -e "$PIDFILE" ] && read PID < "$PIDFILE"

case "$1" in
start) if [ -z "$PID" ] || (( "$(($(date +%s -r "$PIDFILE") - ($(date +%s) - $(cut -f 1 -d'.' < /proc/uptime))))" < 0 )); then
           # if there is no $PID or if the $PIDFILE is older than system's uptime
            [ -e "$LOG" ] && rm "$LOG"
            nohup script/$COMMAND > $LOG 2>&1 &
            PID=$!
            echo -n "Starting server "
            until [ -s "$LOG" ]; do echo -n "."; sleep 1; done
            echo " done"
            cat "$LOG"
            if kill -0 $PID 2> /dev/null; then
                echo $PID > "$PIDFILE"
            else echo "Server died early."
                exit 1
            fi
        else echo "Server was running and yet is." 1>&2
        fi
	;;
stop)	if [ -n "$PID" ] && kill "$PID"; then
            [ -e "$PIDFILE" ] && rm -f $PIDFILE
            echo "Server stopped."
        else echo "Server did not run." 1>&2
        fi
        ;;
restart)
        $0 stop
        sleep 0.5
        $0 start
        ;;
update) if [ "$PID" ]; then $0 stop && git pull && $0 start
        else git pull
        fi
        ;;
status)
        if [ "$PID" ]; then
            echo "Server runs for user $FLOWGENCYTM_USER and" \
                 "listens to $MOJO_LISTEN."
            ps u -p "$PID" --no-headers
            LINES=${2:-20}
            echo "The $LINES most recent lines of log file:"
            tail -$LINES "$LOG"
        else echo "Server is not running."
        fi
        exit 2
        ;;
esac
exit 0
