#!/bin/bash

# Find out the directory in which we reside
cd $( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/..
source local.rc
export FLOWGENCYTM_USER MOJO_LISTEN
[ -e "$PIDFILE" ] && read PID < "$PIDFILE"

case "$1" in
start)	if [ -z "$PID" ]; then
            [ -e "$LOG" ] && rm "$LOG"
            nohup script/$COMMAND > $LOG 2>&1 &
            echo $! > "$PIDFILE"
            echo -n "Starting server "
            until [ -s "$LOG" ]; do echo -n "."; sleep 1; done
            echo " done"
            cat "$LOG"
        else echo "Server was running and yet is" 1>&2
        fi
	;;
stop)	if [ -n "$PID" ] && kill "$PID"; then
            [ -e "$PIDFILE" ] && rm -f $PIDFILE
            echo "Server stopped"
        else echo "Server did not run" 1>&2
        fi
        ;;
restart)
        $0 stop
        $0 start
        ;;
update) if [ "$PID" ]; then $0 stop && git pull && $0 start
        else git pull
        fi
        ;;
status)
        if [ "$PID" ]; then
            echo "Server runs for user $FLOWGENCYTM_USER and" \
                 "listens to $MOJO_LISTEN"
            ps u -p "$PID" --no-headers
        else echo "Server is not running"
        fi
        exit 2
        ;;
esac
exit 0
