#!/usr/bin/env perl

use strict;
use warnings;

#use FindBin;
#BEGIN { chdir("$FindBin::Bin/.."); }
#use lib "lib/";

# Start command line interface for application
require Mojo::Server::Morbo;
Mojo::Server::Morbo->new->run('script/server');
